package com.personalstudyplanner.model;
import java.time.LocalDate;
public class Topic {
 public enum Status { NOT_STARTED, IN_PROGRESS, COMPLETED }
 private final int id; private final String name; private final int difficulty, importance, estimatedMinutes; private final LocalDate deadline; private int progress, pyqFrequency, missedSessions; private double practiceScore; private Status status;
 public Topic(int id,String name,int difficulty,int importance,int estimatedMinutes,LocalDate deadline,int progress){if(name==null||name.isBlank())throw new IllegalArgumentException("Topic name cannot be empty");if(difficulty<1||difficulty>5||importance<1||importance>5)throw new IllegalArgumentException("Difficulty and importance must be 1-5");if(estimatedMinutes<=0)throw new IllegalArgumentException("Estimated time must be positive");this.id=id;this.name=name;this.difficulty=difficulty;this.importance=importance;this.estimatedMinutes=estimatedMinutes;this.deadline=deadline;updateProgress(progress);}
 public void updateProgress(int v){if(v<0||v>100)throw new IllegalArgumentException("Progress must be 0-100");progress=v;status=v==100?Status.COMPLETED:(v==0?Status.NOT_STARTED:Status.IN_PROGRESS);}
 public int remainingMinutes(){return (int)Math.ceil(estimatedMinutes*(100-progress)/100.0);} public int getId(){return id;} public String getName(){return name;} public int getDifficulty(){return difficulty;} public int getImportance(){return importance;} public int getEstimatedMinutes(){return estimatedMinutes;} public LocalDate getDeadline(){return deadline;} public int getProgress(){return progress;} public Status getStatus(){return status;} public int getPyqFrequency(){return pyqFrequency;} public void setPyqFrequency(int v){pyqFrequency=Math.max(0,v);} public double getPracticeScore(){return practiceScore;} public void setPracticeScore(double v){practiceScore=Math.max(0,Math.min(100,v));} public int getMissedSessions(){return missedSessions;} public void incrementMissedSessions(){missedSessions++;}
}
